version: '3.1'

services:
    backend:
        build:
            context: ./backend 
        container_name: backend
        restart: always 
        ports:
            - "8000:8000"
        volumes:
            - .:/backend
            - media_files_volume:/backend/media 
        networks:
            - dbdata_network 
            - nginx_network 
        
        depends_on:
            - dbpostgress  
    
    frontend:
        build:
            context: /frontend 
        container_name: frontend
        restart: always 
        volumes:
            - react_build_volumes:/frontend/build 
        networks:
            - nginx_network
        

    dbpostgress:
        image: postgres:alpine 
        container_name: dbpostgress
        restart: always
        ports:
            - '5432:5432'
        env_file: /backend/.env
        volumes:
            - dbdata:/var/lib/postgresql/data
        networks:
            - dbdata_network
    
    nginx:
        image: nginx:alpine
        container_name: nginx 
        ports:
            - "80:8080"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro 
            -  media_files_volume:/backend/media 
            - react_build_volumes:/var/www/frontend 
        networks:
            - nginx_network
        
        depends_on:
            - backend
            - frontend 

  
volumes:
    dbdata:
        external: true 
    media_files_volume:
        external: true 

    react_build_volumes:
        external: true 
networks:
    dbdata_network:
        external: true
    
    nginx_network:
        external: true 