# Generated by Django 4.1.5 on 2023-02-05 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0003_alter_user_is_active_alter_user_is_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otprequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
