# Generated by Django 4.1.5 on 2023-02-06 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0004_otprequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
